name: build-deploy-dotnet
on: 
  push:
   paths:
     - ".github/workflows/build-and-callresusable-deploy.yml"
     - "./demo-app/**"
  workflow_dispatch: #Manual_Trigger
permissions:
  contents: read 

jobs:
  build-create:
   runs-on: ubuntu-latest
   defaults:
    run: 
      working-directory: ./demo-app
   steps:
     - name: check repository
       uses: actions/checkout@v4
     - name: setup dotnet core
       uses: actions/setup-dotnet@v4.0.1
       with:
         dotnet-version: '9.x'
     - name: Build Code
       run: dotnet build --configuration Release
     - name: Publish Code
       run: dotnet publish -c Release --property:PublishDir="${{env.DOTNET_ROOT}}/myapp"
     - name: Upload Artifact
       uses: actions/upload-artifact@v4
       with:
          # Artifact name
          name: dotnet-app
          path: ${{env.DOTNET_ROOT}}/myapp

  call-resusable-build-deploy:
    needs: build-create
    
    uses: devopsByArneshdey/Actions-Practice_Repo/.github/workflows/resusable-buildtest.yml@shared-wfl
    with:
      package-name: dotnet-app
      app-name: myapp1
      deployment-slot: development-phase
