name: build-deploy-dotnet
on: 
  push:
   paths:
     - ".github/workflows/build-and-deploy.yml"
     - "./demo-app/**"
  workflow_dispatch: #Manual_Trigger
  
jobs:
  build-create:
   runs-on: ubuntu-latest
   steps:
    - name: checkout-repository
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 0 #to get all tags
    - name: docker OR dontainer setup
    - uses: docker/setup-buildx-action@v3
    - run: docker buildx version
    - run: docker buildx list
    
    
    
    
      
